name: MSYS2-MINGW32-RELEASE
on:
  push:
    tags:
     - '**'

jobs:
  msys2-mingw32-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            git
            make
            mingw-w64-i686-gcc
            mingw-w64-i686-SDL
            mingw-w64-i686-gcc-libs
            mingw-w64-i686-libiconv
            mingw-w64-i686-libmad
            mingw-w64-i686-libmikmod
            mingw-w64-i686-libogg
            mingw-w64-i686-libpng
            mingw-w64-i686-libvorbis
            mingw-w64-i686-libwinpthread
            mingw-w64-i686-libxml2
            mingw-w64-i686-openal
            mingw-w64-i686-xz
            mingw-w64-i686-zlib
      - name: Retrieve Git Tag
        id: git-tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          GIT_TAG=${{ steps.git-tag.outputs.tag }}
          wget https://github.com/msys2/msys2-archive/releases/download/2022-12-16-mingw32/mingw-w64-i686-SDL_mixer-1.2.12-9-any.pkg.tar.zst
          pacman --noconfirm -U ./mingw-w64-i686-SDL_mixer-1.2.12-9-any.pkg.tar.zst
          cd src
          touch .depends
          make .depends
          make -j 6
          cd ..
          mkdir artifact2x
          mkdir artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG
          mkdir artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten
          install -s src/*.exe artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/
          for i in \
            SDL.dll \
            libSDL_mixer-1-2-0.dll \
            libgcc_s_dw2-1.dll \
            libiconv-2.dll \
            liblzma-5.dll \
            libmad-0.dll \
            libmikmod-3.dll \
            libogg-0.dll \
            libopenal-1.dll \
            libpng16-16.dll \
            libstdc++-6.dll \
            libvorbis-0.dll \
            libvorbisfile-3.dll \
            libwinpthread-1.dll \
            libxml2-16.dll \
            zlib1.dll \
            ; do
            cp -av /mingw32/bin/"$i" artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/
          done
          mkdir artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/'Ultima IV Dokumentation'
          cp -av 'Ultima IV Dokumentation'/*.pdf.xor artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/'Ultima IV Dokumentation'/
          cp -av 'Ultima IV Dokumentation'/LIESMICH.TXT artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/'Ultima IV Dokumentation'/
          cp -av README.md README.TXT LIESMICH.TXT WINDOWS.TXT RASPBERR.TXT artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/
          cp -av u4.bat artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/u4.bat
          cp -av apple2* AUTHORS COPYING OLD-README border.bmp credits.html fixpal* mirrors.bat MessageBox.js u4.desktop xu4.cfg xu4.spec artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/
          cp -av conf/* artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/
          rm -rf artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/iOS
          mkdir artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/graphics
          cp -av graphics/ega artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/graphics/
          mkdir artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/music
          cp -av music/*.ogg artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/music/
          mkdir artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/sound
          cp -av sound/*.ogg artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/sound/
          cp -a talk artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/
          cp -a src/xu4.ico artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/
          cd src
          sed 's/^# define DEFAULT_SCALE 2$/# define DEFAULT_SCALE 1/' < settings.h > ~/settings2.h
          cp -a settings.h ~/settings.h
          cp -af ~/settings2.h settings.h
          make -j 6
          cd ..
          mkdir artifact1x
          cp -a artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG artifact1x/U4DEU-Win32-1xZoom-$GIT_TAG
          rm -f artifact1x/U4DEU-Win32-1xZoom-$GIT_TAG/Daten/*.exe
          install -s src/*.exe artifact1x/U4DEU-Win32-1xZoom-$GIT_TAG/Daten/
          cd src
          make clean
          rm .depends
          cd ..
          cp -a src artifact1x/U4DEU-Win32-1xZoom-$GIT_TAG/Daten/
          cp -a ~/settings.h src/
          cp -a src artifact2x/U4DEU-Win32-2xZoom-$GIT_TAG/Daten/
          powershell -ExecutionPolicy Bypass -Command '$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut('\''artifact2x\U4DEU-Win32-2xZoom-'$GIT_TAG'\Ultima IV.lnk'\''); $s.TargetPath = '\''%COMSPEC%'\''; $s.Arguments = '\''/c Daten\u4.bat'\''; $s.WindowStyle = 1; $s.IconLocation = '\''%USERPROFILE%\Desktop\U4DEU-Win32-2xZoom-'$GIT_TAG'\Daten\xu4.ico'\''; $s.Save()'
          powershell -ExecutionPolicy Bypass -Command '$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut('\''artifact1x\U4DEU-Win32-1xZoom-'$GIT_TAG'\Ultima IV.lnk'\''); $s.TargetPath = '\''%COMSPEC%'\''; $s.Arguments = '\''/c Daten\u4.bat'\''; $s.WindowStyle = 1; $s.IconLocation = '\''%USERPROFILE%\Desktop\U4DEU-Win32-1xZoom-'$GIT_TAG'\Daten\xu4.ico'\''; $s.Save()'
      - uses: actions/upload-artifact@v4
        with:
          name: U4DEU-Win32-2xZoom-${{ steps.git-tag.outputs.tag }}
          path: artifact2x/
      - uses: actions/upload-artifact@v4
        with:
          name: U4DEU-Win32-1xZoom-${{ steps.git-tag.outputs.tag }}
          path: artifact1x/
